# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
# deleteDatasources:
#  - name: Prometheus # Keep Prometheus if you still want it deleted/reprovisioned
#    orgId: 1
#  - name: Loki # Add Loki here if you need to ensure an old one is deleted first
#    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: Prometheus
  # <string, required> datasource type. Required
  type: prometheus
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: http://prometheus:9090
  # <string> database password, if used
  password:
  # <string> database user, if used
  user:
  # <string> database name, if used
  database:
  # <bool> enable/disable basic auth
  basicAuth: false
  # <string> basic auth username, if used
  basicAuthUser:
  # <string> basic auth password, if used
  basicAuthPassword:
  # <bool> enable/disable with credentials headers
  withCredentials: false
  # <bool> mark as default datasource. Max one per org
  isDefault: true
  # <map> fields that will be converted to json and stored in json_data
  jsonData:
     graphiteVersion: "1.1"
     tlsAuth: false
     tlsAuthWithCACert: false
     # Add Prometheus-specific jsonData fields here if needed
     # httpMethod: "POST" # Example
  # <string> json object of data that will be encrypted.
  secureJsonData:
    tlsCACert: "..."
    tlsClientCert: "..."
    tlsClientKey: "..."
  version: 1
  # <bool> allow users to edit datasources from the UI.
  editable: true

  # Add Loki Datasource
- name: Loki
  type: loki
  access: proxy # Use proxy access mode
  url: http://loki:3100 # URL of the Loki service within the Docker network
  orgId: 1
  jsonData:
    # Optional: Define derived fields for better log exploration in Grafana
    # derivedFields:
    #   - datasourceUid: '<loki-datasource-uid>' # Replace with actual Loki datasource UID after Grafana creates it, if needed for linking
    #     matcherRegex: 'traceId=(\w+)'
    #     name: TraceID
    #     url: '$${__value.raw}'
    #     urlDisplayLabel: 'View Trace'
    maxLines: 1000 # Default maximum lines Grafana will request
  version: 1
  editable: true
  isDefault: false # Prometheus is already default
